### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by drwatsoncode** [devowlio/wp-react-starter#20]
First of all, thank you for all your hard work putting this project together. It is a wonderful collection of tools and technologies.

I am experienced with React, but new to WordPress, and there are some features I expected to find in this starter that are either absent or that I have not been able to find (perhaps due to my inexperience with WordPress).

- **Custom API endpoints** -- The starter project demonstrates how to call and consume the response from the `/plugin` endpoint of the WordPress REST API, but there is no example (that I can see) of creating or consuming a custom endpoint.
**EDIT:** I was wrong. The `inc/rest/Service.class.php` file *does* create a REST endpoint at `/plugin` (under the REST `SERVICE_NAMESPACE`). I was confused because WordPress exposes a built-in REST service at `/plugin`. Perhaps wp-reactjs-starter should use a different name for its example endpoint.
- **Data storage** -- The starter project contains an in-memory Todo list. It would have been better (in my opinion) to have the Todo data persisted in a WordPress table and/or MariaDB.
- **Shortcode** -- Being new to WordPress, it would have been very helpful to me if the starter project demonstrated shortcode creation so the Widget could be inserted in the main content of a page.
- **Cannot use Widget** -- In the Appearance/Widgets admin page, I can see the "React Demo Widget" listed, but I cannot seem to add it to a page. It seems that the only side-bar is the "Footer" and even when I add the widget to that sidebar, nothing shows up on the page. It is highly likely that I am just misunderstanding something about WordPress or your project, but I'm surprised that in the initial state of the project, I cannot seem to find any way to use the React Demo Widget. Shouldn't it be present on the "Hello World" post? If it is there or can be added, please let me know how.
 **EDIT:** I just realized that the widget would have shown up except for a bug -- "*ReferenceError: jQuery is not defined*". I'll post that as a separate issue.

Thank you so much again for your great project. I would very much appreciate if you could clear up my confusion on a few of the issues above. Thanks!

**Comment by matzeeable** [comment]
Hi @drwatsoncode !

Thanks for your comment and feedback. We have worked hard on this project since a few month and released finally a complete rewrite of the boilerplate. If you want to checkout: https://devowlio.gitbook.io/wp-react-starter/ 🙂

- **Custom API endpoints**: Now you will have a `HelloWorld` file which demonstrates a simple REST API endpoint. The known `/plugin` is not part of the `utils` package which is mandatory for the boilerplate itself.

- **Data storage**: This sounds interesting and we should consider this in the future. Since we have released now v2 of the boilerplate we do not work on new features - only focus on bugs.

- **Shortcode**: We are working on video tutorials in the future to showcase how for example shortcodes can be implemented. Generally, create a new endpoint file in your TypeScript source and enqueue it when needed through `Assets`.

- **Cannot use Widget**: This should be fixed with the newest version.

### Are you already using the boilerplate?

If you are already using the boilerplate you need to **manually** migrate to the boilerplate. Since the building process of the plugin itself is still the same you need to migrate your PHP and JS coding. JS should be moved to **TypeScript** as it is is more maintainable and scalable.

Best regards,
Matthew

**Comment by matzeeable** [comment]
Closed due to inactivity. Please reopen.
